CICD
AndrewWestberg/cncli pull request #24
Opened 2021-02-08 13:11 UTC by michaeljfazio

* Added GitHub workflow for CICD on push and merge requests (includes compilation check, linting, code formatting, and clippy checks).
* Update README.md to include compilation instructions.
* Reformatted code according to standard rustfmt rules (enforced in CICD builds).
* Use pkg-config to link libsodium libraries instead of relative path to sub-repo code base.
* Removed libsodium subrepo code base and added libsodium-dev to ubuntu install dependencies in README.md.
* Added conditional compilation check for unit test failing on OSX due to differing expected error message.
* Update all out-of-date dependencies (including those with security notices).

2021-02-08 14:02 UTC, michaeljfazio commented
I'm not going to complete the release workflow as part of this pull request. That can be finished at a later stage. Work remaining is to upload the matrix build artefacts (i.e. cncli binaries) automatically.

2021-02-08 16:43 UTC, AndrewWestberg commented on README.md
> +$ sudo apt-get install -y automake build-essential pkg-config libffi-dev libgmp-dev libssl-dev libtinfo-dev libsystemd-dev zlib1g-dev make g++ tmux git jq wget libncursesw5 libtool autoconf libsodium
I don't think this is correct. We must use the iohk version of libsodium and not the system-installed version. The system-installed version is missing functions we need.

2021-02-08 16:44 UTC, AndrewWestberg commented on build.rs
> +    pkg_config::Config::new().probe("libsodium").unwrap();
If this is relying on the system-installed version of libsodium, it's not the right approach.

2021-02-08 16:45 UTC, AndrewWestberg requested changes
CICD stuff looks good. We need to figure out the right approach for libsodium before merging.

2021-02-09 07:39 UTC, michaeljfazio commented
> CICD stuff looks good. We need to figure out the right approach for libsodium before merging.

All done. I'll update the pull request details accordingly.

2021-02-09 15:39 UTC, AndrewWestberg approved these changes

2021-02-09 15:39 UTC, merged